"""srekit report — generate weekly incident summary via Claude AI."""

import os
from datetime import datetime, timedelta, timezone
from pathlib import Path

import httpx
import typer
from rich.console import Console

console = Console()

AGENT_URL = os.environ.get("SRE_AGENT_URL", "http://localhost:8000")


def report() -> None:
    """Generate a weekly incident summary markdown report via Claude AI."""
    import anthropic

    # Fetch incidents from the last 7 days
    since = (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()

    try:
        resp = httpx.get(
            f"{AGENT_URL}/incidents",
            params={"since": since, "limit": "100"},
            timeout=10,
        )
        resp.raise_for_status()
        incidents = resp.json()
    except httpx.HTTPError as e:
        console.print(f"[red]Failed to fetch incidents: {e}[/]")
        raise typer.Exit(1)

    if not incidents:
        console.print("[yellow]No incidents in the last 7 days. Nothing to report.[/]")
        return

    # Build incident data for the prompt
    incident_lines: list[str] = []
    for inc in incidents:
        incident_lines.append(
            f"- #{inc['id']} | {inc['alert_name']} | severity={inc['severity']} | "
            f"service={inc['service']} | status={inc['status']} | {inc['created_at']}\n"
            f"  Root cause: {inc.get('root_cause', 'N/A')[:300]}\n"
            f"  Recommendation: {inc.get('recommendation', 'N/A')[:300]}\n"
            f"  Remediation: {inc.get('remediation_action') or 'None'}"
        )
    incident_data = "\n\n".join(incident_lines)

    prompt = (
        "You are an SRE lead writing a weekly incident summary for stakeholders.\n\n"
        f"Period: {since[:10]} to {datetime.now(timezone.utc).strftime('%Y-%m-%d')}\n"
        f"Total incidents: {len(incidents)}\n\n"
        f"Incident details:\n{incident_data}\n\n"
        "Write a concise executive summary in markdown format with these sections:\n"
        "1. **Overview** — one paragraph summary\n"
        "2. **Key Incidents** — the most impactful incidents and what happened\n"
        "3. **Trends** — patterns observed (recurring alerts, common root causes)\n"
        "4. **Action Items** — concrete follow-ups to prevent recurrence\n\n"
        "Keep it professional and under 500 words."
    )

    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        console.print("[red]ANTHROPIC_API_KEY environment variable is not set.[/]")
        raise typer.Exit(1)

    console.print("[bold]Generating weekly report...[/]")

    try:
        client = anthropic.Anthropic(api_key=api_key)
        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=2048,
            messages=[{"role": "user", "content": prompt}],
        )
        report_content = message.content[0].text
    except Exception as e:
        console.print(f"[red]Claude API call failed: {e}[/]")
        raise typer.Exit(1)

    # Save report
    reports_dir = Path("./reports")
    reports_dir.mkdir(exist_ok=True)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    report_path = reports_dir / f"{date_str}.md"

    header = (
        f"# Weekly Incident Report — {date_str}\n\n"
        f"_Generated by srekit report_\n\n"
        f"---\n\n"
    )
    report_path.write_text(header + report_content + "\n")

    console.print(f"[green]Report saved to {report_path}[/]")
    console.print()
    console.print(report_content)
